#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android.Resource", IsApplication=false)]

namespace Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int accessToken = 2130771969;
			
			// aapt resource value: 0x7f010002
			public static int centerLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public static int centerLng = 2130771971;
			
			// aapt resource value: 0x7f010000
			public static int mapid = 2130771968;
			
			// aapt resource value: 0x7f010005
			public static int uiControls = 2130771973;
			
			// aapt resource value: 0x7f010004
			public static int zoomLevel = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public static int black = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int white = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int clusteri = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int defpin = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int direction_arrow = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int location_marker = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public static int tooltip_description = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int tooltip_subdescription = 2131099650;
			
			// aapt resource value: 0x7f060000
			public static int tooltip_title = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int tooltip = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public static int ApplicationName = 2131034117;
			
			// aapt resource value: 0x7f050004
			public static int Hello = 2131034116;
			
			// aapt resource value: 0x7f050000
			public static int mapboxAndroidSDKVersion = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int toolTipAddress = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int toolTipDescription = 2131034114;
			
			// aapt resource value: 0x7f050003
			public static int toolTipTitle = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MapView = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 1
			public static int MapView_accessToken = 1;
			
			// aapt resource value: 2
			public static int MapView_centerLat = 2;
			
			// aapt resource value: 3
			public static int MapView_centerLng = 3;
			
			// aapt resource value: 0
			public static int MapView_mapid = 0;
			
			// aapt resource value: 5
			public static int MapView_uiControls = 5;
			
			// aapt resource value: 4
			public static int MapView_zoomLevel = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
